SOURCE_PATH = src
CLASS_PATH = build/classes
JAR_PATH = build/stylechecker.jar
STYLECHECK_PATH = $(SOURCE_PATH)/stylecheck
STYLECHECKERS_PATH = $(STYLECHECK_PATH)/stylecheckers
STYLECHECK_CLASS_PATH = $(STYLECHECK_PATH)/StyleCheck.class
STYLECHECK_SRC_PATH = $(STYLECHECK_PATH)/StyleCheck.java
LINE_LENGTH_CHECKER_SRC_PATH = $(STYLECHECKERS_PATH)/LineLengthChecker.java
IMPORT_CHECKER_SRC_PATH = $(STYLECHECKERS_PATH)/ImportChecker.java
INDENTATION_CHECKER_SRC_PATH = $(STYLECHECKERS_PATH)/IndentationChecker.java
NONEMPTY_BLOCKS_CHECKER_SRC_PATH = $(STYLECHECKERS_PATH)/NonemptyBlocksChecker.java
OPTIONAL_BRACES_CHECKER_SRC_PATH = $(STYLECHECKERS_PATH)/OptionalBracesChecker.java
PACKAGE_CHECKER_SRC_PATH = $(STYLECHECKERS_PATH)/PackageChecker.java

all: jar run
.PHONY: all

jar: $(STYLECHECK_CLASS_PATH)
	jar cf $(JAR_PATH) -C $(CLASS_PATH) .
.PHONY: jar

run: jar
	java -cp build/stylechecker.jar stylecheck.StyleCheck
.PHONY: run

$(STYLECHECK_CLASS_PATH): $(STYLECHECK_SRC_PATH) $(LINE_LENGTH_CHECKER_SRC_PATH) \
                          $(IMPORT_CHECKER_SRC_PATH) $(INDENTATION_CHECKER_SRC_PATH) \
                          $(NONEMPTY_BLOCKS_CHECKER_SRC_PATH) $(OPTIONAL_BRACES_CHECKER_SRC_PATH) \
                          $(PACKAGE_CHECKER_SRC_PATH)
	javac -d $(CLASS_PATH) $< $(LINE_LENGTH_CHECKER_SRC_PATH) $(IMPORT_CHECKER_SRC_PATH) \
	$(INDENTATION_CHECKER_SRC_PATH) $(NONEMPTY_BLOCKS_CHECKER_SRC_PATH) \
	$(OPTIONAL_BRACES_CHECKER_SRC_PATH) $(PACKAGE_CHECKER_SRC_PATH)

clean:
	rm -rf build
.PHONY: clean